# 服务配置
server:
  port: 21090
  servlet:
    context-path: /api/v1.0/campus-news-api
# API地址前缀，用于接口拦截放行
my-server:
  api-context-path: /api/v1.0/campus-news-api
#MySQL与文件上传限制配置
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus-news-sytem?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
# Mybatis Plus配置
mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启日志
    map-underscore-to-camel-case: true # 开启驼峰命名
  global-config:
    db-config:
      id-type: auto # 主键策略
  mapper-locations: classpath*:/mapper/**/*.xml # mapper文件位置




